---
abstract: 'Build and install Net-SNMP'
author:
  - 'Eric A. Miller <emiller AT cpan DOT org>'
build_requires:
  Test::CChecker: '0'
  Test::More: '0.94'
  perl: '5.010001'
configure_requires:
  Alien::Base: '0.020'
  ExtUtils::CChecker: '0.10'
  File::ShareDir: '1.03'
  Module::Build: '0.42'
  PkgConfig: '0.14026'
  Test2::Suite: '0.000067'
  perl: '5.010001'
dynamic_config: 1
generated_by: 'Module::Build version 0.422, CPAN::Meta::Converter version 2.143240'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-SNMP-MAXTC
provides:
  Alien::SNMP::MAXTC:
    file: lib/Alien/SNMP/MAXTC.pm
    version: '0.02'
requires:
  Alien::Base: '0.020'
  File::ShareDir: '1.03'
  parent: '0'
  perl: '5.010001'
resources:
  license: http://opensource.org/licenses/BSD-3-Clause
version: '0.02'
